version: '3.9'

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - ./docker/db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    cap_add:
      - SYS_NICE
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD} 
      UPLOAD_LIMIT: 64M
  # Wordpress
  wordpress:
    depends_on:
      - db
      - mailhog
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '8000:80'
    restart: always
    volumes: [
      './:/var/www/html',
      './docker/wp-uploads:/var/www/html/wp-content/uploads'
    ]
    links:
      - mailhog      
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
